from app.ui.widgets.actions import control_actions
from app.ui.widgets.actions import gpu_settings_actions
from app.ui.widgets.actions import graphics_view_actions
from app.ui.widgets.actions import pipeline_profile_actions as pprofile_settings
import cv2
from typing import Any

_PIPELINE_PROFILE_ACTIVE_OPTIONS = (
    pprofile_settings.PIPELINE_PROFILE_DISPLAY_MODE_OVERLAY,
    pprofile_settings.PIPELINE_PROFILE_DISPLAY_MODE_DOCK,
    pprofile_settings.PIPELINE_PROFILE_DISPLAY_MODE_BOTH,
)

SETTINGS_LAYOUT_DATA: Any = {  # noqa: F811
    "Appearance": {
        "ThemeSelection": {
            "level": 1,
            "label": "Theme",
            "options": [
                "True-Dark",
                "OLED-Black",
                "Windows11-Dark",
                "Dark",
                "Dark-Blue",
                "Light",
                "Solarized-Dark",
                "Solarized-Light",
                "Dracula",
                "Nord",
                "Gruvbox",
                "Monokai",
            ],
            "default": "True-Dark",
            "help": "Select the theme to be used",
            "exec_function": control_actions.change_theme,
            "exec_function_args": [],
        }
    },
    "General": {
        "ProvidersPrioritySelection": {
            "level": 1,
            "label": "Providers Priority",
            "options": ["CUDA", "TensorRT", "TensorRT-Engine", "CPU"],
            "default": "TensorRT",
            "help": "Execution providers: try TensorRT vs Custom and measure with VISIOMASTER_PERF_BUNDLE=1. FP16/mixed precision: profile with ORT or Nsight before changing builds. Engine cache: set VISIOMASTER_LOG_TRT_CACHE=1 on load to print cache-hit lines.",
            "exec_function": control_actions.change_execution_provider,
            "exec_function_args": [],
        },
        "TrtDynamicBatchTuningToggle": {
            "level": 1,
            "label": "Tune TensorRT dynamic batch profiles (ORT TensorRT EP)",
            "default": False,
            "help": "When on, the sliders below set min/opt/max **batch** axes for ORT TensorRT dynamic shape profiles "
            "(Inswapper128 / GhostFace / HyperSwap, ArcFace from ONNX, LivePortrait motion & stitch). "
            "When off, use environment variables VISIOMASTER_TRT_MAX_BATCH_* / OPT_* only. "
            "**Reload** affected ONNX models (or restart) after changing values so engines rebuild.",
        },
        "TrtMaxBatchSwapSlider": {
            "level": 2,
            "label": "TRT max batch: swap (Inswapper / Ghost / Hyper)",
            "min_value": "1",
            "max_value": "32",
            "default": "16",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Upper bound for batched swap tiles. Lower → faster TRT builds and less VRAM; raise if you routinely process many faces per frame.",
        },
        "TrtOptBatchSwapSlider": {
            "level": 2,
            "label": "TRT opt batch: swap",
            "min_value": "1",
            "max_value": "32",
            "default": "4",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "TensorRT ‘optimization’ batch for swap models; must be ≤ max. Typical: 2–4 for few faces, up to max for heavy multi-face.",
        },
        "TrtMaxBatchArcfaceSlider": {
            "level": 2,
            "label": "TRT max batch: ArcFace (Inswapper128ArcFace)",
            "min_value": "1",
            "max_value": "32",
            "default": "16",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Max batch for ArcFace ONNX when TRT profiles are inferred from the graph.",
        },
        "TrtOptBatchArcfaceSlider": {
            "level": 2,
            "label": "TRT opt batch: ArcFace",
            "min_value": "1",
            "max_value": "32",
            "default": "8",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Optimization batch for ArcFace; must be ≤ max batch.",
        },
        "TrtMaxBatchLpMotionSlider": {
            "level": 2,
            "label": "TRT max batch: LivePortrait motion (img)",
            "min_value": "1",
            "max_value": "8",
            "default": "8",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Capped at 8 to match the Python batch cap for motion extraction.",
        },
        "TrtOptBatchLpMotionSlider": {
            "level": 2,
            "label": "TRT opt batch: LivePortrait motion",
            "min_value": "1",
            "max_value": "8",
            "default": "2",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Must be ≤ max motion batch.",
        },
        "TrtMaxBatchLpStitchSlider": {
            "level": 2,
            "label": "TRT max batch: LivePortrait stitch / eye / lip",
            "min_value": "1",
            "max_value": "16",
            "default": "12",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Batch axis for LP stitching inputs (concatenated keypoint features).",
        },
        "TrtOptBatchLpStitchSlider": {
            "level": 2,
            "label": "TRT opt batch: LivePortrait stitch",
            "min_value": "1",
            "max_value": "16",
            "default": "4",
            "step": 1,
            "parentToggle": "TrtDynamicBatchTuningToggle",
            "requiredToggleValue": True,
            "help": "Must be ≤ max stitch batch.",
        },
        "MultiGpuRoutingEnableToggle": {
            "level": 1,
            "label": "Use multiple GPUs for frame routing",
            "default": False,
            "help": "When on, the pipeline can assign frames across the GPUs selected below (round-robin). The primary GPU (next control) is always included. When off, every frame uses the primary GPU only (environment variable VISIOMASTER_EMULATE_MULTI_GPU still enables extra logical devices for testing).",
            "exec_function": gpu_settings_actions.on_multi_gpu_routing_toggle,
            "exec_function_args": [],
        },
        "GpuPrimaryDeviceSelection": {
            "level": 1,
            "label": "Primary GPU",
            "default": 0,
            "help": "Main CUDA device for TensorRT/CUDA providers and cache paths. Shown by device name; this GPU always participates in routing and cannot be unchecked below.",
        },
        "GpuRoutingTargetsPicker": {
            "level": 2,
            "label": "Additional GPUs for routing",
            "help": "Visible when “Use multiple GPUs…” is on. Check extra physical GPUs, “Emulated GPU”, and/or “CPU” to mix CUDA and CPU ORT in the round-robin. The primary GPU row stays checked and disabled. CPU is slower but can offload some frames from the GPU.",
            "parentToggle": "MultiGpuRoutingEnableToggle",
            "requiredToggleValue": True,
        },
        "MultiGpuAdvancedToggle": {
            "level": 2,
            "label": "Advanced multi-GPU scheduling",
            "default": False,
            "parentToggle": "MultiGpuRoutingEnableToggle",
            "requiredToggleValue": True,
            "help": "Unlock proportional scheduling (weighted round-robin), per-GPU worker counts, auto calibration and live metrics. Recommended when GPUs differ in speed (e.g. 5070 Ti + 3070): pure round-robin is bottlenecked by the slowest GPU.",
        },
        "GpuLoadBalancingModeSelection": {
            "level": 2,
            "label": "Load balancing mode",
            "options": [
                "Round-Robin",
                "Weighted Manual",
                "Weighted Auto",
                "Hybrid",
            ],
            "default": "Round-Robin",
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "Round-Robin: 1 frame per GPU (current behavior). Weighted Manual: obey the weights below. Weighted Auto: measure ms/frame per GPU and rebuild weights. Hybrid: Weighted Auto + idle workers can steal frames from a busy peer GPU (recommended for asymmetric setups).",
            "exec_function": gpu_settings_actions.on_load_balancing_mode_changed,
            "exec_function_args": [],
        },
        "GpuWeightsEditor": {
            "level": 2,
            "label": "Weights per GPU",
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "Relative share of frames per GPU (integers, 1..16). Ex.: 5070 Ti = 3 / 3070 = 1 -> the fast GPU receives three frames for every one that goes to the slow GPU. Ignored in Round-Robin mode.",
        },
        "GpuThreadsPerGpuEditor": {
            "level": 2,
            "label": "Worker threads per GPU (optional)",
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "Leave rows at 0 to let the engine split ‘Number of Threads’ by weight. Set an explicit count per GPU only to hard-pin e.g. 3 workers to the fast GPU and 1 to the slow GPU.",
        },
        "GpuAutoBenchmarkOnStartToggle": {
            "level": 2,
            "label": "Auto-benchmark on start",
            "default": False,
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "When enabled (and mode is Weighted Auto / Hybrid), run a short warm-up per GPU at the start of a run to seed the weights before real frames flow through. Adds ~1–3 s to startup but avoids the cold-start penalty where the slow GPU briefly dominates routing.",
        },
        "GpuAutoWeightsReweightEveryNFramesSlider": {
            "level": 2,
            "label": "Re-weight every N frames",
            "min_value": "0",
            "max_value": "5000",
            "default": "600",
            "step": 100,
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "In Weighted Auto / Hybrid, recompute weights from rolling ms/frame every N frames. 0 disables runtime re-weighting (weights stay at whatever the benchmark or manual input set).",
        },
        "GpuLiveMetricsOverlayToggle": {
            "level": 2,
            "label": "Show per-GPU live metrics",
            "default": False,
            "parentToggle": "MultiGpuAdvancedToggle",
            "requiredToggleValue": True,
            "help": "Adds a small panel showing FPS / ms-per-frame / queue size per logical GPU (including the CPU-ORT slot). Useful to verify the weights are actually keeping both GPUs busy.",
        },
        "GpuLiveMetricsPanel": {
            "level": 2,
            "label": "Live metrics (per GPU)",
            "parentToggle": "GpuLiveMetricsOverlayToggle",
            "requiredToggleValue": True,
            "help": "Rolling per-GPU FPS, ms/frame (EMA) and subqueue depth. Updates every 500 ms while processing; stays idle otherwise.",
        },
        "nThreadsSlider": {
            "level": 1,
            "label": "Number of Threads",
            "min_value": "1",
            "max_value": "30",
            "default": "4",
            "step": 1,
            "help": "Worker pool threads for playback/recording (face pipeline). If the profile overlay shows the frame queue pegged with 1 thread, try 2; more threads can raise GPU contention—compare session summaries on stop.",
            "exec_function": control_actions.change_threads_number,
            "exec_function_args": [],
        },
        "KeepControlsToggle": {
            "level": 1,
            "label": "Keep Controls Active",
            "default": False,
            "help": "Keep the controls active during recording.",
        },
        "TrackMarkersToggle": {
            "level": 1,
            "label": "Track Markers on Video Seek",
            "default": False,
            "help": "Update parameters and controls when seeking the video to reflect the options status for it's position.",
        },
        "GlobalInputResizeToggle": {
            "level": 1,
            "label": "Resize Input Source (Performance/Output)",
            "default": False,
            "help": "Rescales the input video/image BEFORE processing (downscale for performance or upscale with quality-oriented interpolation). Sets the pipeline output resolution to the selected size.",
        },
        "GlobalInputResizeSizeSelection": {
            "level": 2,
            "label": "Input Resolution Target",
            "options": [
                "240p",
                "360p",
                "480p",
                "540p",
                "720p",
                "1080p",
                "1440p",
                "2160p",
            ],
            "default": "720p",
            "parentToggle": "GlobalInputResizeToggle",
            "requiredToggleValue": True,
            "help": "Target height in lines (240p–2160p). The aspect ratio is preserved.",
        },
        "RecordOutputDecoupleResizeToggle": {
            "level": 2,
            "label": "Record output at different resolution (preview vs file)",
            "default": False,
            "parentToggle": "GlobalInputResizeToggle",
            "requiredToggleValue": True,
            "help": "When on, preview and AI still use Input Resolution Target above; each encoded frame is "
            "resized (Lanczos) to Record output resolution before FFmpeg. Improves preview FPS while keeping "
            "a higher-resolution file. Virtual camera and on-screen preview stay at preview resolution.",
        },
        "RecordOutputResizeSizeSelection": {
            "level": 3,
            "label": "Record output resolution (height)",
            "options": [
                "240p",
                "360p",
                "480p",
                "540p",
                "720p",
                "1080p",
                "1440p",
                "2160p",
            ],
            "default": "1080p",
            "parentToggle": "RecordOutputDecoupleResizeToggle",
            "requiredToggleValue": True,
            "help": "Target height in lines for the recorded MP4 (aspect ratio matches the pipeline frame). "
            "Typically set higher than Input Resolution Target (e.g. preview 540p, record 1080p).",
        },
        "FrameWorkerDelayDecimalSlider": {
            "level": 1,
            "label": "Frame Worker Delay",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "0.2",
            "step": 0.1,
            "decimals": 1,
            "help": "Delay in seconds before AI processing when seeking in video. Prevents GPU overload and stuttering.",
        },
        "PerformancePresetSelection": {
            "level": 1,
            "label": "Performance preset (video)",
            "options": [
                "Custom (no preset)",
                "High FPS — 720p input, interval 3, det 416, Inswapper 128",
                "Multi-face @ 720p — ArcFace cap + match boost",
                "Single face @ 1080p — quality",
                "Balanced — 1080p resize, interval 2",
                "Light — 540p, interval 4, tight ArcFace",
                "Webcam / baja latencia — 480p, det 1, Inswapper 128, ArcFace mínimo",
            ],
            "default": "Custom (no preset)",
            "help": "Applies a coordinated bundle (resize, detection interval, detector side, ArcFace/lazy/cap, "
            "match boost, optional Inswapper 128). Does not change swapper model choice except the High FPS "
            "preset. Use VISIOMASTER_PERF_BUNDLE=1 to measure impact.",
            "exec_function": control_actions.apply_performance_preset_selection,
            "exec_function_args": [],
        },
        "PipelineProfileDisplayModeSelection": {
            "level": 1,
            "label": "Pipeline profile (timing)",
            "options": list(pprofile_settings.PIPELINE_PROFILE_DISPLAY_MODES),
            "default": pprofile_settings.PIPELINE_PROFILE_DISPLAY_MODE_OFF,
            "help": "Where to show per-stage timings (feeder + worker). Preview overlay draws on the video; "
            "dock opens a side panel (good for long tables). Either or both collects the same data. "
            "On stop, prints [PIPELINE-PROFILE-SESSION] to the console. Optional: "
            "VISIOMASTER_PIPELINE_PROFILE_CSV=file.csv; VISIOMASTER_PERF_STAGES=1; VISIOMASTER_PIPELINE_METRICS=1; "
            "VISIOMASTER_ORT_PER_SESSION_LOCK=1 (experimental). Inswapper128: VISIOMASTER_INSWAPPER_ORT_BATCH; "
            "plane multi-face prefetch + primary restorer: VISIOMASTER_RESTORER_ORT_BATCH.",
            "exec_function": graphics_view_actions.on_pipeline_profile_display_mode_changed,
            "exec_function_args": [],
        },
        "PipelineProfileAggregationSelection": {
            "level": 2,
            "label": "Profile aggregation",
            "options": ["EMA", "Window"],
            "default": "EMA",
            "parentSelection": "PipelineProfileDisplayModeSelection",
            "requiredSelectionIn": _PIPELINE_PROFILE_ACTIVE_OPTIONS,
            "help": "EMA: exponential moving average per stage. Window: mean of the last N frames.",
        },
        "PipelineProfileWindowFramesSlider": {
            "level": 2,
            "label": "Profile window (frames)",
            "min_value": "5",
            "max_value": "120",
            "default": "30",
            "step": 1,
            "parentSelection": "PipelineProfileDisplayModeSelection",
            "requiredSelectionIn": _PIPELINE_PROFILE_ACTIVE_OPTIONS,
            "help": "Number of frames for Window mode; also bounds history for EMA updates.",
        },
        "PipelineProfileEmaAlphaDecimalSlider": {
            "level": 2,
            "label": "EMA alpha",
            "min_value": "0.05",
            "max_value": "0.95",
            "default": "0.25",
            "step": 0.05,
            "decimals": 2,
            "parentSelection": "PipelineProfileDisplayModeSelection",
            "requiredSelectionIn": _PIPELINE_PROFILE_ACTIVE_OPTIONS,
            "help": "Smoothing factor for EMA (higher = react faster to changes).",
        },
        "PipelineProfileGpuSyncToggle": {
            "level": 2,
            "label": "CUDA sync between stages (accurate, slower)",
            "default": False,
            "parentSelection": "PipelineProfileDisplayModeSelection",
            "requiredSelectionIn": _PIPELINE_PROFILE_ACTIVE_OPTIONS,
            "help": "Call cuda.synchronize() at each stage mark for faithful GPU times; reduces preview FPS.",
        },
        "PipelineProfileOverlayGlobalMeanColumnToggle": {
            "level": 2,
            "label": "Profile table: single column (mean across workers)",
            "default": False,
            "parentSelection": "PipelineProfileDisplayModeSelection",
            "requiredSelectionIn": _PIPELINE_PROFILE_ACTIVE_OPTIONS,
            "help": "Show Stage | Mean only — same values as the old Avg column, without one column per "
            "worker thread. Easier to read when using several threads; per-thread detail is hidden.",
            "exec_function": graphics_view_actions.on_pipeline_profile_global_mean_column_toggle,
            "exec_function_args": [],
        },
        "PipelineInflightBufferMultiplierSlider": {
            "level": 1,
            "label": "Inflight buffer (× preroll)",
            "min_value": "2",
            "max_value": "24",
            "default": "4",
            "step": 1,
            "help": "Frame queue max ≈ preroll × this value (preroll scales with worker threads). "
            "Higher = more overlap between feeder and workers if RAM allows; lower = less latency/RAM.",
        },
        "PipelineSeparateCudaStreamsToggle": {
            "level": 1,
            "label": "Separate CUDA streams (feeder vs workers)",
            "default": False,
            "help": "Use dedicated CUDA streams for feeder detection and worker inference to improve "
            "GPU overlap on some drivers. If unstable, turn off. For Nsight: set VISIOMASTER_NVTX=1.",
        },
        "ArcFaceBatchInferenceToggle": {
            "level": 1,
            "label": "Batch ArcFace (2+ faces, Inswapper128 path)",
            "default": True,
            "help": "When several faces need embeddings on the same frame, run one batched ORT call "
            "(Inswapper128ArcFace + Opal/Pearl, non-Custom). Falls back per-face if batch fails.",
        },
        "PerformanceArcFaceCenterBiasSlider": {
            "level": 1,
            "label": "ArcFace cap: center bias (0–100)",
            "min_value": "0",
            "max_value": "100",
            "default": "0",
            "step": 5,
            "help": "When max ArcFace/frame limits which faces run, boost priority for faces near "
            "the frame center (0 = area only).",
        },
        "PerformanceArcFaceMatchedTrackBoostSlider": {
            "level": 1,
            "label": "ArcFace cap: boost recently matched tracks (0–100)",
            "min_value": "0",
            "max_value": "100",
            "default": "0",
            "step": 5,
            "help": "When a ByteTrack id had a swap/edit match within the “matched track memory” "
            "window below, multiply its priority score by (1 + this/100) so it is less likely to "
            "lose a slot when max ArcFace/frame is tight. 0 = off.",
        },
        "PerformanceRecognitionMatchedTrackMemorySlider": {
            "level": 1,
            "label": "Matched-track memory (frames)",
            "min_value": "8",
            "max_value": "180",
            "default": "48",
            "step": 4,
            "help": "How long a track stays “recently matched” for cap boost and for matched-only "
            "ArcFace stride (below). Larger = stickier priority / reuse; cuts or new faces fall out "
            "naturally after this many frames without a new match note.",
        },
        "PerformanceMatchedTrackArcfaceStrideSlider": {
            "level": 1,
            "label": "Matched tracks: min frames between real ArcFace",
            "min_value": "1",
            "max_value": "12",
            "default": "1",
            "step": 1,
            "help": "1 = off. For ByteTrack ids that matched a target within matched-track memory, "
            "reuse the last embedding without ArcFace until this many frames have passed since the "
            "last *fresh* ArcFace (same idea as global lazy track, but only for faces you are already "
            "swapping). Geometry cache and scene-cut refresh still apply first.",
        },
        "PerformanceSceneCutArcFaceRefreshEnableToggle": {
            "level": 1,
            "label": "Scene cut → force fresh ArcFace (1 frame)",
            "default": True,
            "help": "If the downscaled luminance histogram jumps, skip lazy track reuse once so "
            "embeddings refresh after hard cuts.",
        },
        "PerformanceSceneCutHistogramDiffDecimalSlider": {
            "level": 2,
            "label": "Scene cut histogram L1 threshold",
            "min_value": "0.1",
            "max_value": "0.9",
            "default": "0.35",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "PerformanceSceneCutArcFaceRefreshEnableToggle",
            "requiredToggleValue": True,
            "help": "Higher = fewer false scene cuts; lower = more refreshes.",
        },
        "PerformanceSwapperAutoresHysteresisEnableToggle": {
            "level": 1,
            "label": "Swapper auto-res: hysteresis (Inswapper128)",
            "default": False,
            "help": "When auto input resolution is on, avoid flickering 128↔512 by requiring extra "
            "scale/motion margin before changing resolution (per ByteTrack id).",
        },
        "PerformanceSwapperAutoresMotionEmaDecimalSlider": {
            "level": 2,
            "label": "Hysteresis motion EMA alpha",
            "min_value": "0.05",
            "max_value": "0.95",
            "default": "0.35",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "PerformanceSwapperAutoresHysteresisEnableToggle",
            "requiredToggleValue": True,
            "help": "Tunes the scale deadband when downgrading auto-res tier: lower alpha = wider margin "
            "(stick to the previous resolution longer); higher alpha = tighter margin (react sooner).",
        },
        "PerformanceDetectTrackRoiEnableToggle": {
            "level": 1,
            "label": "Detection: track-guided ROI on skip frames",
            "default": False,
            "help": "When Face Detection Interval > 1 and ByteTrack ids exist, run RetinaFace on a "
            "padded crop around the last bbox instead of the full frame on skip frames. Full-frame "
            "detection still runs on interval boundaries.",
        },
        "PerformanceDetectTrackRoiPadPercentSlider": {
            "level": 2,
            "label": "Track ROI pad (% of max(w,h))",
            "min_value": "20",
            "max_value": "120",
            "default": "55",
            "step": 5,
            "parentToggle": "PerformanceDetectTrackRoiEnableToggle",
            "requiredToggleValue": True,
            "help": "Padding around the union of previous-frame track boxes before clamping to image.",
        },
        "ModelEvictIdleMinutesSlider": {
            "level": 1,
            "label": "Unload idle ONNX models after (minutes, 0=off)",
            "min_value": "0",
            "max_value": "120",
            "default": "0",
            "step": 5,
            "help": "Periodic check: models not used for this many minutes may be unloaded unless "
            "Keep models alive is on. Does not unload the active swapper mid-playback.",
        },
        "ModelWarmupOnLoadToggle": {
            "level": 1,
            "label": "Warm up model after load (1 dummy inference)",
            "default": False,
            "help": "Runs a minimal TensorRT/ONNX bind after a successful load to reduce first-frame hitch.",
        },
        "PerformanceRecognitionEmbeddingsFp16Toggle": {
            "level": 1,
            "label": "Store recognition embeddings as FP16 in RAM",
            "default": False,
            "help": "Reduces CPU cache footprint; values promoted to FP32 before ArcFace-related math.",
        },
    },
    "Output Settings": {
        "OutputToTargetLocationToggle": {
            "level": 1,
            "label": "Output to Target Location",
            "default": False,
            "help": "Save processed output next to the current target media instead of the global output folder.",
        },
        "ClusterOutputBySourceToggle": {
            "level": 1,
            "label": "Cluster Output by Source Name",
            "default": False,
            "help": "Save processed output into a subfolder named after the selected merged embedding.",
        },
    },
    "Video Playback Settings": {
        "VideoPlaybackCustomFpsToggle": {
            "level": 1,
            "label": "Set Custom Video Playback FPS",
            "default": False,
            "help": "Manually set the FPS to be used when playing the video",
            "exec_function": control_actions.set_video_playback_fps,
            "exec_function_args": [],
        },
        "VideoPlaybackCustomFpsSlider": {
            "level": 2,
            "label": "Video Playback FPS",
            "min_value": "1",
            "max_value": "120",
            "default": "30",
            "parentToggle": "VideoPlaybackCustomFpsToggle",
            "requiredToggleValue": True,
            "step": 1,
            "help": "Set the maximum FPS of the video when playing",
        },
        "VideoPlaybackBufferingToggle": {
            "level": 1,
            "label": "Playback Buffering",
            "default": False,
            "help": "Activates buffering for smoother video playback.",
        },
        "VideoPlaybackLoopToggle": {
            "level": 1,
            "label": "Playback Loop",
            "default": False,
            "help": "Auto start over when video playing to the end.(Not work for recording)",
        },
        "VideoPlaybackBenchSameFrameToggle": {
            "level": 1,
            "label": "Benchmark: repeat same frame",
            "default": False,
            "help": "Preview only (not recording): decodes once at the current timeline position, then runs "
            "detect+swap on copies of that frame forever until you stop. Timeline/slider stays on that frame; "
            "internal frame indices advance for buffering. Use with Pipeline profile / VISIOMASTER_PERF_* for "
            "stable GPU benchmarks.",
        },
        "PreviewFrameGenEnableToggle": {
            "level": 1,
            "label": "Frame Interpolation",
            "default": False,
            "help": "Preview and virtual cam only: smoother motion between processed frames. Linear: "
            "decoupled OpenGL crossfade. Neural: decoupled RIFE off the GUI thread. Use “Preview steps per frame” "
            "for smoothness; metronome subdivides so playback speed stays correct. Recording writes only full "
            "processed frames. If preview drifts vs Live Sound, try disabling sync.",
            "exec_function": control_actions.handle_preview_frame_interpolation_toggle,
            "exec_function_args": ["PreviewFrameGenEnableToggle"],
        },
        "FrameInterpolationMethodSelection": {
            "level": 2,
            "label": "Interpolation method",
            "options": ["Linear (GPU)", "Neural (ONNX)"],
            "default": "Linear (GPU)",
            "parentToggle": "PreviewFrameGenEnableToggle",
            "requiredToggleValue": True,
            "help": "Linear (GPU): OpenGL decoupled preview (steps per frame below). Virtual cam off "
            "(needs a CPU frame path). Neural (ONNX): RIFE off the GUI thread with the same step cadence; "
            "GPU-heavy; same preview/virtual-cam scope, not written to recording files.",
            "exec_function": control_actions.handle_frame_interpolation_method_change,
            "exec_function_args": ["FrameInterpolationMethodSelection"],
        },
        "PreviewNeuralInterpolationModelSelection": {
            "level": 3,
            "label": "Neural ONNX checkpoint",
            "options": ["RifePreviewInterp", "RifePreviewInterpAlt"],
            "default": "RifePreviewInterp",
            "parentToggle": "PreviewFrameGenEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FrameInterpolationMethodSelection",
            "requiredSelectionValue": "Neural (ONNX)",
            "help": "Dos ranuras RIFE (TensorStack): misma arquitectura; la alternativa permite sustituir el archivo en interp/ sin tocar el predeterminado.",
            "exec_function": control_actions.handle_preview_neural_interp_model_change,
            "exec_function_args": ["PreviewNeuralInterpolationModelSelection"],
        },
        "PreviewInterpolationStepsPerFrameSelection": {
            "level": 2,
            "label": "Preview steps per frame",
            "options": ["2", "3", "4", "5", "6"],
            "default": "2",
            "parentToggle": "PreviewFrameGenEnableToggle",
            "requiredToggleValue": True,
            "help": "Single smoothness control for Linear and Neural: display substeps per processed frame "
            "(2–6; capped vs video FPS so total rate stays ≤ ~240 Hz). Linear: more steps = smoother crossfade. "
            "Neural: same cadence; RIFE timestep = 1/steps. Webcam/screen coupled preview uses K = steps − 1.",
            "exec_function": control_actions.handle_preview_interpolation_steps_per_frame_change,
            "exec_function_args": ["PreviewInterpolationStepsPerFrameSelection"],
        },
        "PreviewLinearBlendShaderSelection": {
            "level": 3,
            "label": "Linear blend quality",
            "options": [
                "sRGB mix",
                "Linear (gamma)",
                "Luma-weighted",
                "Edge-aware",
                "Pro (linear + luma + edges)",
            ],
            "default": "sRGB mix",
            "parentToggle": "PreviewFrameGenEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FrameInterpolationMethodSelection",
            "requiredSelectionValue": "Linear (GPU)",
            "help": "OpenGL fragment shader path for linear interpolation (video preview). "
            "sRGB mix: direct blend (fastest). Linear (gamma): blend in linear light. "
            "Luma-weighted: re-weight mix by local luminance (reduces some ghosting). "
            "Edge-aware: soften blend weight on strong edges (few extra taps). "
            "Pro: luma-weighted + edge-aware. Neural (RIFE) mode ignores this.",
        },
        "PreviewFsr1EnableToggle": {
            "level": 1,
            "label": "FSR 1 preview (OpenGL)",
            "default": False,
            "help": "AMD FidelityFX Super Resolution 1.x (EASU + RCAS) on the main video preview only. "
            "Off when Virtual Camera is on or when Linear (GPU) frame interpolation is active. "
            "Does not change recording or exported files.",
            "exec_function": control_actions.handle_preview_fsr1_toggle,
            "exec_function_args": ["PreviewFsr1EnableToggle"],
        },
        "PreviewFsr1SharpnessDecimalSlider": {
            "level": 2,
            "label": "FSR1 RCAS sharpness",
            "min_value": "0.00",
            "max_value": "2.00",
            "default": "0.35",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "PreviewFsr1EnableToggle",
            "requiredToggleValue": True,
            "help": "RCAS sharpening strength (0 = very soft, ~0.35 typical, 2 = strong).",
            "exec_function": control_actions.handle_preview_fsr1_sharpness_change,
            "exec_function_args": ["PreviewFsr1SharpnessDecimalSlider"],
        },
        "PreviewFsr1ShadersEnableToggle": {
            "level": 2,
            "label": "FSR1: EASU+RCAS shaders",
            "default": True,
            "parentToggle": "PreviewFsr1EnableToggle",
            "requiredToggleValue": True,
            "help": "On: full FSR 1 pipeline (EASU upscale + RCAS sharpen). Off: same OpenGL path but only "
            "a simple texture draw — use to see if problems come from FSR shaders or from viewport/textures/setup.",
            "exec_function": control_actions.handle_preview_fsr1_shaders_toggle,
            "exec_function_args": ["PreviewFsr1ShadersEnableToggle"],
        },
        "PreviewFsr1SourceScalePercentSlider": {
            "level": 2,
            "label": "FSR1 preview source scale (%)",
            "min_value": "25",
            "max_value": "100",
            "default": "100",
            "step": "5",
            "parentToggle": "PreviewFsr1EnableToggle",
            "requiredToggleValue": True,
            "help": "Preview only: scales down the frame sent to FSR before EASU upscales to the on-screen size. "
            "Below 100% the upscale is stronger so the effect is easier to see; 100% is normal (full-res source).",
            "exec_function": control_actions.handle_preview_fsr1_source_scale_change,
            "exec_function_args": ["PreviewFsr1SourceScalePercentSlider"],
        },
        "PreviewNisEnableToggle": {
            "level": 1,
            "label": "NIS preview (OpenGL compute)",
            "default": False,
            "help": "NVIDIA Image Scaling (NVScaler) on the main video preview only. "
            "Requires OpenGL 4.3+ and works best when the preview is larger than the source "
            "(otherwise a simple blit is used). Mutually exclusive with FSR 1 preview. "
            "Does not change recording or exported files.",
            "exec_function": control_actions.handle_preview_nis_toggle,
            "exec_function_args": ["PreviewNisEnableToggle"],
        },
        "PreviewNisSharpnessDecimalSlider": {
            "level": 2,
            "label": "NIS sharpness",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.50",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "PreviewNisEnableToggle",
            "requiredToggleValue": True,
            "help": "NVScaler sharpness (0–1, SDK range; ~0.5 is neutral).",
            "exec_function": control_actions.handle_preview_nis_sharpness_change,
            "exec_function_args": ["PreviewNisSharpnessDecimalSlider"],
        },
        "PreviewNisShadersEnableToggle": {
            "level": 2,
            "label": "NIS: NVScaler compute",
            "default": True,
            "parentToggle": "PreviewNisEnableToggle",
            "requiredToggleValue": True,
            "help": "On: NVScaler compute shader (true NIS upscale+sharpen). Off: same viewport path "
            "but only a texture blit — use to test GL setup vs compute.",
            "exec_function": control_actions.handle_preview_nis_shaders_toggle,
            "exec_function_args": ["PreviewNisShadersEnableToggle"],
        },
        "PreviewNisSourceScalePercentSlider": {
            "level": 2,
            "label": "NIS preview source scale (%)",
            "min_value": "25",
            "max_value": "100",
            "default": "100",
            "step": "5",
            "parentToggle": "PreviewNisEnableToggle",
            "requiredToggleValue": True,
            "help": "Preview only: downscale the frame before NIS so upscale is stronger; 100% is normal.",
            "exec_function": control_actions.handle_preview_nis_source_scale_change,
            "exec_function_args": ["PreviewNisSourceScalePercentSlider"],
        },
        "FrameSkipStepSlider": {
            "level": 1,
            "label": "Frame Skip Step",
            "min_value": "1",
            "max_value": "300",
            "default": "30",
            "step": "1",
            "help": "Number of frames to skip when using forward/rewind buttons or the mouse wheel.",
            "exec_function": control_actions.update_video_slider_step,
            "exec_function_args": [],
        },
        "LiveSoundVolumeDecimalSlider": {
            "level": 1,
            "label": "Audio Playback Volume",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "step": 0.01,
            "decimals": 2,
            "help": "Set the playback audio of the audio, when Live Sound is enabled",
        },
        "LiveSoundDelayDecimalSlider": {
            "level": 1,
            "label": "Audio Start Delay (Seconds)",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "0.30",
            "step": 0.01,
            "decimals": 2,
            "help": "Set the audio starting delay to adjust for latency.",
        },
        "VideoPlaybackAudioSyncPreviewToggle": {
            "level": 1,
            "label": "Sync preview to live audio",
            "default": False,
            "help": "Preview only: when Live Sound is on, drive the preview timeline from "
            "the same wall-clock origin as ffplay (container fps × playback speed), so video "
            "stays aligned with what you hear. If swap/decode lags, the feeder catches up in "
            "several small seeks (smoother than one big jump). Disable for classic metronome "
            "pacing. No effect without Live Sound or while recording.",
        },
        "VideoPlaybackAudioSyncMinLagSlider": {
            "level": 2,
            "label": "Audio sync — min lag (frames)",
            "min_value": "2",
            "max_value": "60",
            "default": "8",
            "parentToggle": "VideoPlaybackAudioSyncPreviewToggle",
            "requiredToggleValue": True,
            "step": 1,
            "help": "Start catch-up only when preview is at least this many frames behind the "
            "audio timeline. Higher = fewer seeks, more risk of visible desync before action.",
        },
        "VideoPlaybackAudioSyncCatchupSlicesSlider": {
            "level": 2,
            "label": "Audio sync — spread lag over (steps)",
            "min_value": "2",
            "max_value": "15",
            "default": "5",
            "parentToggle": "VideoPlaybackAudioSyncPreviewToggle",
            "requiredToggleValue": True,
            "step": 1,
            "help": "Roughly how many seeks to close each lag gap (larger = smaller steps per seek, smoother).",
        },
        "VideoPlaybackAudioSyncMaxStepSlider": {
            "level": 2,
            "label": "Audio sync — max frames per seek",
            "min_value": "2",
            "max_value": "90",
            "default": "12",
            "parentToggle": "VideoPlaybackAudioSyncPreviewToggle",
            "requiredToggleValue": True,
            "step": 1,
            "help": "Cap on how many frames one catch-up seek may skip. Lower = gentler; very low may "
            "struggle if the pipeline is much slower than realtime.",
        },
        "VideoPlaybackAudioSyncMinSeekIntervalDecimalSlider": {
            "level": 2,
            "label": "Audio sync — min seek interval (s)",
            "min_value": "0.01",
            "max_value": "0.30",
            "default": "0.04",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "VideoPlaybackAudioSyncPreviewToggle",
            "requiredToggleValue": True,
            "help": "Minimum time between catch-up seeks. Higher reduces seek thrashing; lower reacts faster.",
        },
    },
    "Video Recording Settings": {
        "FrameEnhancerDownToggle": {
            "level": 1,
            "label": "Frame resize to 1920*1080",
            "default": False,
            "help": "Select to resize the video to 1920*1080 (only on 16/9 format)",
        },
        "OpenOutputToggle": {
            "level": 1,
            "label": "Open Output Folder After Recording",
            "default": False,
            "help": "Opens the output folder after recording ends.",
        },
        "PostRecordFrameGenEnableToggle": {
            "level": 1,
            "label": "Post-record frame generation (FFmpeg minterpolate)",
            "default": False,
            "help": "After the final file is written, run a second FFmpeg pass with the minterpolate "
            "filter to increase frame rate (motion-compensated). Re-encodes video with libx264 (yuv420p); "
            "audio is copied. Slower; HDR/10-bit masters may need this off. Preview/virtual cam unchanged.",
        },
        "PostRecordFrameGenFPSMultSelection": {
            "level": 2,
            "label": "Frame-gen FPS multiplier",
            "options": ["2", "3", "4"],
            "default": "2",
            "parentToggle": "PostRecordFrameGenEnableToggle",
            "requiredToggleValue": True,
            "help": "Target output FPS ≈ source FPS × multiplier (capped at 120). Higher = smoother motion but slower encode.",
        },
        "HDREncodeToggle": {
            "level": 1,
            "label": "HDR Encoding - Use on HDR videos only (CPU)",
            "default": False,
            "help": "Encode the video file in HDR, uses CPU and libx256, slower processing.",
        },
        "FFMpegOptionsToggle": {
            "level": 1,
            "label": "FFMpeg options",
            "default": False,
            "help": "Show FFMpeg options.",
        },
        "FFPresetsSDRSelection": {
            "level": 2,
            "label": "Presets SDR",
            "options": ["p1", "p2", "p3", "p4", "p5", "p6", "p7"],
            "default": "p5",
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "HEVC_NVENC presets, P1 = faster but lower quality → P7 = slower but better quality. Default = P5.",
        },
        "FFPresetsHDRSelection": {
            "level": 2,
            "label": "Presets HDR",
            "options": [
                "ultrafast",
                "superfast",
                "veryfast",
                "faster",
                "fast",
                "medium",
                "slow",
                "veryslow",
            ],
            "default": "slow",
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "LIBx265 presets, Ultrafast = faster but lower quality → Veryslow = slower but better quality. Default = Slow.",
        },
        "FFQualitySlider": {
            "level": 2,
            "label": "Quality",
            "min_value": "0",
            "max_value": "51",
            "default": "18",
            "step": 1,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "Constant quality slider, lower values = better quality but less encoding (bigger files). Default = 18.",
        },
        "FFSpatialAQToggle": {
            "level": 2,
            "label": "Spatial AQ",
            "default": False,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "Spatial AQ adjusts the QP within a single frame based on content complexity. It allocates more bits to detailed or textured areas and fewer bits to flat, uniform areas.",
        },
        "FFTemporalAQToggle": {
            "level": 2,
            "label": "Temporal AQ",
            "default": False,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "Temporal AQ adjusts the QP across multiple frames over time. It helps maintain a consistent visual quality by mitigating fluctuations in bitrate and quality between frames.",
        },
    },
    "Swap settings": {
        "AutoSwapToggle": {
            "level": 1,
            "label": "Auto Swap",
            "default": False,
            "help": "Automatically Swap all faces using selected Source Faces/Embeddings when loading an video/image file",
        },
        "KeepInputToggle": {
            "level": 1,
            "label": "Keep Selected Input Faces / Embeddings",
            "default": False,
            "help": "Keep the selected Input Faces Or Embeddings when switching Target Media.",
        },
        "SwapOnlyBestMatchEnableToggle": {
            "level": 1,
            "label": "Swap Input Face only once",
            "default": False,
            "help": "When OFF (default), every detected face that meets its target card's Similarity Threshold can be swapped (several faces in one frame). When ON, at most one detection per target card is swapped — the highest similarity among those that pass the threshold. Similarity Threshold still applies in both modes.",
        },
        "VR180ModeEnableToggle": {
            "level": 1,
            "label": "Enable VR180 Mode",
            "default": False,
            "help": "Enable VR180 mode. This will treat the input video as an equirectangular VR180 video and apply face swapping within perspective crops.",
        },
        "VR180EyeModeSelection": {
            "level": 1,
            "label": "VR180 Eye Mode",
            "options": ["Both Eyes", "Single Eye"],
            "default": "Both Eyes",
            "help": "Select 'Both Eyes' for standard VR180 video (left+right eye side-by-side). Select 'Single Eye' if the input video already contains only one eye's equirectangular view (full frame = one hemisphere).",
            "parentToggle": "VR180ModeEnableToggle",
            "requiredToggleValue": True,
        },
        "VR180TileDetectionToggle": {
            "level": 1,
            "label": "VR Tiled Face Detection",
            "default": False,
            "help": "Run face detection on a grid of 24 undistorted perspective crops to catch faces missed by standard detection (faces near poles, the ±180° seam, or very close to the camera). OFF by default — adds ~24 extra detector runs per keyframe. Enable only when standard detection misses faces.",
            "parentToggle": "VR180ModeEnableToggle",
            "requiredToggleValue": True,
        },
        "VR180MaxFOVSlider": {
            "level": 1,
            "label": "VR Max Crop FOV",
            "min_value": "60",
            "max_value": "150",
            "default": "120",
            "step": 5,
            "help": "Maximum field-of-view for per-face perspective crops. Increase for close-up or near-camera faces (previously hard-capped at 100°). Default: 120°.",
            "parentToggle": "VR180ModeEnableToggle",
            "requiredToggleValue": True,
        },
        "VR180CropResolutionSelection": {
            "level": 1,
            "label": "VR Crop Resolution",
            "options": ["512", "768", "1024"],
            "default": "512",
            "help": "Resolution of perspective crops used for face swapping. Higher values improve quality on high-resolution VR content at the cost of VRAM and processing time.",
            "parentToggle": "VR180ModeEnableToggle",
            "requiredToggleValue": True,
        },
        "MaxDFMModelsSlider": {
            "level": 1,
            "label": "Maximum DFM Models to use",
            "min_value": "1",
            "max_value": "5",
            "default": "1",
            "step": 1,
            "help": "Set the maximum number of DFM Models to keep in memory at a time. Set this based on your GPU's VRAM",
        },
        "EmbMergeMethodSelection": {
            "level": 1,
            "label": "Embedding Merge Method",
            "options": ["Mean", "Median"],
            "default": "Mean",
            "help": 'Select the method to merge facial embeddings. "Mean" averages the embeddings, while "Median" selects the middle value, providing more robustness to outliers.',
        },
    },
    "Detectors": {
        "RecognitionModelSelection": {
            "level": 1,
            "label": "Recognition Model",
            "options": [
                "Inswapper128ArcFace",
                "SimSwapArcFace",
                "GhostArcFace",
                "CSCSArcFace",
            ],
            "default": "Inswapper128ArcFace",
            "help": "Choose the ArcFace model to be used for comparing the similarity of faces. During swapping, the app picks the recognition backbone that matches the active swapper (e.g. HyperSwap and ReHiFace-S use Inswapper128ArcFace, same as Inswapper128). ArcFace alignment is pose-aware (automatic) for robust matching.",
        },
        "DetectorModelSelection": {
            "level": 1,
            "label": "Face Detect Model",
            "options": ["RetinaFace", "Yolov8", "SCRFD", "Yunet", "Yunet-2023"],
            "default": "RetinaFace",
            "help": "Select the face detection model. To benchmark alternatives, use the same video and VISIOMASTER_PERF_BUNDLE=1; keep RecognitionModel matched to the swapper (e.g. Inswapper128ArcFace with Inswapper128).",
            "exec_function": control_actions.on_detector_model_selection_change,
            "exec_function_args": [],
        },
        "DetectorScoreSlider": {
            "level": 1,
            "label": "Detect Score",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "help": "Set the confidence score threshold for face detection. Higher values ensure more confident detections but may miss some faces.",
        },
        "FaceDetectionIntervalSlider": {
            "level": 1,
            "label": "Detection Interval (Frames)",
            "min_value": "1",
            "max_value": "30",
            "default": "1",
            "step": 1,
            "help": "How often to run the full face detector. Higher values improve FPS but may lose fast-moving faces. 1 = Detect every frame (Slowest).",
        },
        "DetectorInternalSizeSelection": {
            "level": 1,
            "label": "Detector internal size",
            "options": [
                "512",
                "416",
                "384",
                "320",
                "256",
                "224",
                "192",
                "160",
                "128",
            ],
            "default": "512",
            "help": "Shown only when the selected detector accepts a variable letterbox (dynamic ONNX). Yolo/Yunet use 640×640 in code; fixed-shape RetinaFace/SCRFD use the model’s compiled side — the control is hidden and the value is set automatically.",
        },
        "MaxFacesToDetectSlider": {
            "level": 1,
            "label": "Max No of Faces to Detect",
            "min_value": "1",
            "max_value": "50",
            "default": "20",
            "step": 1,
            "help": "Set the maximum number of faces to detect in a frame",
        },
        "PerformanceFastDetectEnableToggle": {
            "level": 1,
            "label": "Performance: cap detector internal size",
            "default": False,
            "help": "When enabled, the detector letterbox side is the minimum of your "
            "'Detector internal size' and the cap below. Faster feeder / detection; "
            "small or distant faces may be missed or less stable.",
        },
        "PerformanceFastDetectCapSideSelection": {
            "level": 2,
            "label": "Fast-detect max side (px)",
            "options": ["416", "384", "320", "256"],
            "default": "384",
            "parentToggle": "PerformanceFastDetectEnableToggle",
            "requiredToggleValue": True,
            "help": "Upper bound for detector input side when the cap above is enabled.",
        },
        "PerformanceRecognitionMaxArcFacePerFrameSlider": {
            "level": 1,
            "label": "Performance: max ArcFace runs per frame (0 = all)",
            "min_value": "0",
            "max_value": "16",
            "default": "0",
            "step": 1,
            "help": "After geometry cache and lazy track reuse, at most this many faces still "
            "missing an embedding get a new ArcFace this frame (largest boxes first). 0 = no limit. "
            "If a face is skipped but ByteTrack has a prior embedding, that stale embedding is "
            "reused so swap can still run.",
        },
        "PerformanceRecognitionLazyArcFaceIntervalSlider": {
            "level": 1,
            "label": "Performance: min frames between real ArcFace (track), 1=off",
            "min_value": "1",
            "max_value": "15",
            "default": "1",
            "step": 1,
            "help": "When >1 and ByteTrack IDs exist, after geometry cache misses reuse the last "
            "embedding for the same track without running ArcFace until this many frames have "
            "passed since the last *new* ArcFace for that track. Saves GPU when faces move enough "
            "to miss IoU/kps thresholds; risk of wrong target match on fast cuts or identity "
            "changes. Without tracking (no ids), this path does not apply.",
        },
        "AutoRotationToggle": {
            "level": 1,
            "label": "Auto Rotation",
            "default": False,
            "help": "Automatically rotate the input to detect faces in various orientations.",
        },
        "ManualRotationEnableToggle": {
            "level": 1,
            "label": "Manual Rotation",
            "default": False,
            "help": "Rotate the face detector to better detect faces at different angles.",
        },
        "ManualRotationAngleSlider": {
            "level": 2,
            "label": "Rotation Angle",
            "min_value": "0",
            "max_value": "270",
            "default": "0",
            "step": 90,
            "parentToggle": "ManualRotationEnableToggle",
            "requiredToggleValue": True,
            "help": "Set this to the angle of the input face angle to help with laying down/upside down/etc. Angles are read clockwise.",
        },
        "LandmarkDetectToggle": {
            "level": 1,
            "label": "Enable Landmark Detection",
            "default": False,
            "help": "Enable or disable facial landmark detection, which is used to refine face alignment.",
            "exec_function": control_actions.handle_landmark_state_change,
            "exec_function_args": ["LandmarkDetectToggle"],
        },
        "LandmarkDetectModelSelection": {
            "level": 2,
            "label": "Landmark Detect Model",
            "options": ["5", "68", "3d68", "98", "106", "203", "478"],
            "default": "203",
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "Select the landmark detection model, where different models detect varying numbers of facial landmarks.",
            "exec_function": control_actions.handle_landmark_model_selection_change,
            "exec_function_args": ["LandmarkDetectModelSelection"],
        },
        "LandmarkDetectScoreSlider": {
            "level": 2,
            "label": "Landmark Detect Score",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "Set the confidence score threshold for facial landmark detection.",
        },
        "DetectFromPointsToggle": {
            "level": 2,
            "label": "Detect From Points",
            "default": False,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "Enable detection of faces from specified landmark points.",
        },
        "LandmarkMeanEyesToggle": {
            "level": 2,
            "label": "Use Mean Eyes",
            "default": False,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "Increases stability by averaging multiple points for eyes (Recommended for 203/478 models).",
        },
        "ShowLandmarksEnableToggle": {
            "level": 1,
            "label": "Show Landmarks",
            "default": False,
            "help": "Show Landmarks in realtime.",
        },
        "ShowAllDetectedFacesBBoxToggle": {
            "level": 1,
            "label": "Show Bounding Boxes",
            "default": False,
            "help": "Draw bounding boxes to all detected faces in the frame",
        },
        "KPSSmoothingEnableToggle": {
            "level": 1,
            "label": "Enable KPS Smoothing",
            "default": False,
            "help": "Enable temporal smoothing for facial keypoints (KPS) to reduce jittering and stabilize the face.",
        },
        "KPSEmaAlphaSlider": {
            "level": 2,
            "label": "EMA Alpha",
            "min_value": "1",
            "max_value": "100",
            "default": "35",
            "step": 1,
            "parentToggle": "KPSSmoothingEnableToggle",
            "requiredToggleValue": True,
            "help": "Controls the smoothing rigidity. Lower = more stable but lags, Higher = more responsive but may jitter. Default: 35.",
        },
    },
    "Face Tracking": {
        "FaceTrackingEnableToggle": {
            "level": 1,
            "label": "Enable Face Tracking (ByteTrack)",
            "default": False,
            "help": "Uses ByteTrack to maintain face identities across frames. Improves stability during occlusions and allows lower detection thresholds.",
            "exec_function": control_actions.handle_face_detector_tracking_reset,
            "exec_function_args": [],
        },
        "ByteTrackTrackThreshSlider": {
            "level": 2,
            "label": "Track Threshold",
            "min_value": "10",
            "max_value": "90",
            "default": "40",
            "step": 5,
            "parentToggle": "FaceTrackingEnableToggle",
            "requiredToggleValue": True,
            "help": "Minimum detection confidence to enter the high-confidence tracking pool (value ÷ 100). Lower values track more faces but may include false positives. Changing this resets the tracker.",
            "exec_function": control_actions.handle_face_detector_tracking_reset,
            "exec_function_args": [],
        },
        "ByteTrackMatchThreshSlider": {
            "level": 2,
            "label": "Match Threshold",
            "min_value": "10",
            "max_value": "99",
            "default": "80",
            "step": 5,
            "parentToggle": "FaceTrackingEnableToggle",
            "requiredToggleValue": True,
            "help": "IoU overlap threshold for matching detections to existing tracks (value ÷ 100). Lower values allow looser matching across frames. Changing this resets the tracker.",
            "exec_function": control_actions.handle_face_detector_tracking_reset,
            "exec_function_args": [],
        },
        "ByteTrackTrackBufferSlider": {
            "level": 2,
            "label": "Track Buffer (Frames)",
            "min_value": "1",
            "max_value": "120",
            "default": "30",
            "step": 1,
            "parentToggle": "FaceTrackingEnableToggle",
            "requiredToggleValue": True,
            "help": "Number of frames a lost track is remembered before being removed. Higher values handle longer occlusions but use more memory. Changing this resets the tracker.",
            "exec_function": control_actions.handle_face_detector_tracking_reset,
            "exec_function_args": [],
        },
        "ShowByteTrackBBoxToggle": {
            "level": 1,
            "label": "Show ByteTrack Bounding Boxes",
            "default": False,
            "help": "Draw ByteTrack tracked bounding boxes in orange. Use instead of 'Show Bounding Boxes' when face tracking is enabled.",
            "parentToggle": "FaceTrackingEnableToggle",
            "requiredToggleValue": True,
        },
    },
    "Frame Enhancer": {
        "FrameEnhancerEnableToggle": {
            "level": 1,
            "label": "Enable Frame Enhancer",
            "default": False,
            "help": "Enable frame enhancement for video inputs to improve visual quality.",
            "exec_function": control_actions.handle_frame_enhancer_state_change,
            "exec_function_args": ["FrameEnhancerEnableToggle"],
        },
        "FrameEnhancerTypeSelection": {
            "level": 2,
            "label": "Frame Enhancer Type",
            "options": [
                "CAS-Light",
                "RealEsrgan-x2-Plus",
                "RealEsrgan-x4-Plus",
                "RealEsr-General-x4v3",
                "BSRGan-x2",
                "BSRGan-x4",
                "UltraSharp-x4",
                "UltraMix-x4",
                "SPAN-4x",
                "SPAN-F-4x",
                "DDColor-Artistic",
                "DDColor",
                "DeOldify-Artistic",
                "DeOldify-Stable",
                "DeOldify-Video",
            ],
            "default": "RealEsrgan-x2-Plus",
            "parentToggle": "FrameEnhancerEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "Select the frame enhancement model. CAS-Light is a fast GPU sharpen (CAS-style, no ONNX); "
                "use Blend to mix with the original. SPAN-4x / SPAN-F-4x are light SR models. "
                "For stronger detail use RealEsrgan-x4-Plus, UltraSharp-x4, or BSRGan-x4 (higher GPU cost)."
            ),
            "exec_function": control_actions.handle_enhancer_model_selection_change,
            "exec_function_args": ["FrameEnhancerTypeSelection"],
        },
        "FrameEnhancerBlendSlider": {
            "level": 2,
            "label": "Blend",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FrameEnhancerEnableToggle",
            "requiredToggleValue": True,
            "help": "Blends the enhanced results back into the original frame.",
        },
        "FrameEnhancerTemporalSmoothSlider": {
            "level": 2,
            "label": "Video temporal smooth",
            "min_value": "0",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "FrameEnhancerEnableToggle",
            "requiredToggleValue": True,
            "help": "Reduces frame-to-frame flicker from per-frame upscalers by blending with the previous displayed frame (ordered playback). Resets on seeks, buffer flushes, non-sequential frames, or large scene changes. 0 = off.",
        },
    },
    "Webcam and Virtualcam Settings": {
        "ScreenCaptureMonitorSelection": {
            "level": 2,
            "label": "Captura de pantalla — monitor (índice mss)",
            "options": ["0", "1", "2", "3", "4", "5", "6"],
            "default": "1",
            "help": "Índice mss: 1 = pantalla principal; 2+ = monitores extra; 0 = escritorio virtual completo (todos los monitores).",
        },
        "ScreenCaptureMaxFPSSelection": {
            "level": 2,
            "label": "Captura de pantalla — FPS objetivo",
            "options": ["15", "23", "30", "60"],
            "default": "30",
            "help": "Velocidad objetivo de vista previa; resoluciones altas pueden ir más lentas.",
        },
        "ScreenCaptureRegionModeSelection": {
            "level": 2,
            "label": "Captura de pantalla — modo de región",
            "options": ["Full monitor", "Custom region"],
            "default": "Full monitor",
            "help": "Monitor completo o región rectangular. En modo personalizado use el campo de texto o el botón para dibujar en pantalla.",
        },
        "ScreenCaptureRegionRectText": {
            "level": 2,
            "label": "Región (izq, arriba, ancho, alto)",
            "default": "",
            "width": 220,
            "help": "Píxeles en coordenadas de escritorio global (como mss). Ejemplo: 100,100,1280,720. Pulse «Dibujar región» para elegir con el ratón.",
            "parentSelection": "ScreenCaptureRegionModeSelection",
            "requiredSelectionValue": "Custom region",
        },
        "ScreenCapturePickRegionScreenAction": {
            "level": 2,
            "label": "Selección de región",
            "button_label": "Dibujar región en pantalla…",
            "help": "Pantalla completa atenuada: arrastre un rectángulo sobre el área a capturar. Escape cancela.",
            "click_handler": control_actions.start_screen_capture_region_picker,
            "parentSelection": "ScreenCaptureRegionModeSelection",
            "requiredSelectionValue": "Custom region",
        },
        "WebcamMaxNoSelection": {
            "level": 2,
            "label": "Webcam Max No",
            "options": ["1", "2", "3", "4", "5", "6"],
            "default": "1",
            "help": "Select the maximum number of webcam streams to allow for face swapping.",
        },
        "WebcamBackendSelection": {
            "level": 2,
            "label": "Webcam Backend",
            "options": ["Default", "DirectShow", "MSMF", "V4L", "V4L2", "GSTREAMER"],
            "default": "Default",
            "help": "Choose the backend for accessing webcam input.",
        },
        "WebcamMaxResSelection": {
            "level": 2,
            "label": "Webcam Resolution",
            "options": [
                "480x360",
                "640x480",
                "1280x720",
                "1920x1080",
                "2560x1440",
                "3840x2160",
            ],
            "default": "1280x720",
            "help": "Select the maximum resolution for webcam input.",
        },
        "WebCamMaxFPSSelection": {
            "level": 2,
            "label": "Webcam FPS",
            "options": ["23", "30", "60"],
            "default": "30",
            "help": "Set the maximum frames per second (FPS) for webcam input. For live preview/virt cam, "
            "stale frames waiting before face detection are dropped so the GPU works on the freshest capture "
            "(set VISIOMASTER_LIVE_DROP_LOG=1 to log drops).",
        },
        "SendVirtCamFramesEnableToggle": {
            "level": 1,
            "label": "Send Frames to Virtual Camera",
            "default": False,
            "help": "Send the swapped video/webcam output to virtual camera for using in external applications",
            "exec_function": control_actions.toggle_virtualcam,
            "exec_function_args": [],
        },
        "VirtCamBackendSelection": {
            "level": 1,
            "label": "Virtual Camera Backend",
            "options": ["obs", "unitycapture"],
            "default": "obs",
            "help": "Choose the backend based on the Virtual Camera you have set up",
            "parentToggle": "SendVirtCamFramesEnableToggle",
            "requiredToggleValue": True,
            "exec_function": control_actions.enable_virtualcam,
            "exec_funtion_args": [],
        },
    },
    "Misc": {
        "KeepModelsAliveToggle": {
            "level": 1,
            "label": "Keep Loaded Models in Memory",
            "default": False,
            "help": "Stops the models from automatically unloading when changing settings, only with CLEAR GPU button.",
        },
        "TargetMediaFolderRecursiveToggle": {
            "level": 1,
            "label": "Target Media Include Subfolders",
            "default": False,
            "help": "Include all files from Subfolders when choosing Target Media Folder",
        },
        "InputFacesFolderRecursiveToggle": {
            "level": 1,
            "label": "Input Faces Include Subfolders",
            "default": False,
            "help": "Include all files from Subfolders when choosing Input Faces Folder",
        },
        "ImageFormatToggle": {
            "level": 1,
            "label": "Save Output Image in JPG Format",
            "default": False,
            "help": "Saves the output image from Save Image or Batch Process to JPG format instead of PNG.",
        },
        "CommandLineDebugEnableToggle": {
            "level": 1,
            "label": "Commandline Infos",
            "default": False,
            "help": "used restore strenght and needed itterations in Commandline + jpeg/mpeg infos",
        },
        "AutoSaveWorkspaceToggle": {
            "level": 1,
            "label": "Auto Save Workspace",
            "default": False,
            "help": "Auto Saves Workspace .json in output folder at end of recording (only the status at end of recording)",
        },
        "AutoLoadWorkspaceToggle": {
            "level": 1,
            "label": "Auto Load Last Workspace",
            "default": False,
            "help": 'Do not show the "load last workspace" dialog when open then app, always load last workspace.',
        },
        "DilatationTypeSelection": {
            "level": 1,
            "label": "Mask Dilatation Type",
            "options": ["conv", "pool", "iter_pool"],
            "default": "conv",
            "help": "Max_Pool2d is faster but conv2d is more precise (especially on higher dilatation values)",
        },
    },
    "Experimental Settings (very experimental, better don´t touch)": {
        "ActivateexperimentalsettingsEnableToggle": {
            "level": 1,
            "label": "Experimental settings",
            "default": False,
            "help": "Enable AutoColor Transfer: 1. Hans Test without mask, 2. Hans Test with mask, 3. DFL Method without mask, 4. DFL Original Method.",
        },
        "AnalyseImageEnableToggle": {
            "level": 2,
            "label": "Analyse Image",
            "default": False,
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Image analysis",
        },
        #        'DFLXSegBGEnableToggle': {
        #            'level': 2,
        #            'label': 'Xseg 2 Background',
        #            'default': False,
        #            'parentToggle': 'ActivateexperimentalsettingsEnableToggle',
        #            'requiredToggleValue': True,
        #            'help': 'Enable second XSeg Mask for Inside the Face. not working well atm. (uses Faceparser on swap)'
        #        },
        #        'OccluderMaskBgSlider': {
        #            'level': 3,
        #            'label': 'Xseg 2 Background Adjust',
        #            'min_value': '-40',
        #            'max_value': '40',
        #            'default': '-10',
        #            'step': 1,
        #            'parentToggle': 'DFLXSegBGEnableToggle',
        #            'requiredToggleValue': True,
        #            'help': 'Adjust where the second Xseg Mask gets applied.'
        #        },
        "get_cropped_face_kpsTypeSelection": {
            "level": 2,
            "label": "get cropped face kps",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "original_face_128_384TypeSelection": {
            "level": 2,
            "label": "original_128_384",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "original_face_512TypeSelection": {
            "level": 2,
            "label": "original_512",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "UntransformTypeSelection": {
            "level": 2,
            "label": "Untransform",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "ScalebackFrameTypeSelection": {
            "level": 2,
            "label": "Scaleback Frame",
            "options": ["NEAREST", "BILINEAR", "BICUBIC"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "expression_faceeditor_t256TypeSelection": {
            "level": 2,
            "label": "Expression_faceeditor_t256",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "expression_faceeditor_backTypeSelection": {
            "level": 2,
            "label": "Expression_faceeditor_back",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "block_shiftTypeSelection": {
            "level": 2,
            "label": "block shift",
            "options": ["NEAREST", "BILINEAR"],
            "default": "NEAREST",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! for basic functionality testing. changes the interpolation type for necessary pipeline functions (resize/rotation/etc. of image). caution, influences Autorestore calculation",
        },
        "AntialiasTypeSelection": {
            "level": 2,
            "label": "Antialias",
            "options": ["False", "True"],
            "default": "False",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "Experimental! most of the time no visual effect, in rare cases minor effect",
        },
    },
}

CAMERA_BACKENDS = {
    "Default": cv2.CAP_ANY,
    "DirectShow": cv2.CAP_DSHOW,
    "MSMF": cv2.CAP_MSMF,
    "V4L": cv2.CAP_V4L,
    "V4L2": cv2.CAP_V4L2,
    "GSTREAMER": cv2.CAP_GSTREAMER,
}
